# file = open("example.txt", "r")
# print(file.readline())
# print(file.readline())
# file = open("example.txt", "r")
# print(file.read())
# print(file.readlines())
# file.close()
# data = file.read()
# words = data.split()
# len(file.readlines())
# file = open("example.txt", "a")
# file.write("I love programming!")
# file.close()

# file = open("example.txt", "r")
# print(file.read())
file = open("report.txt", "a")

file.write("Quote was said by Gandhi")